# Linear Regression Multiple Variable

## ie3

In [77]:
import pandas as pd
import math
from sklearn import linear_model
df = pd.read_csv("homeprices2.csv")
print(df)
median_bedrooms = math.floor(df.bedrooms.median())
print(median_bedrooms)
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
3
   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000


In [78]:
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression as LM
X = df.drop(["price"], axis="columns")
y = df.price
print(type(x))

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=23)
print(type(X_train))
print(len(X_test))

reg = LM()
reg.fit(X_train, y_train)
print(reg.score(X_test, y_test))
print(reg.coef_)
print(reg.intercept_)
print(reg.predict([[3000, 3, 15]]))
print(reg.predict([[2500, 3, 15]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
2
0.8322115384615385
[   86.25     0.   -4125.  ]
408249.9999999999
[605125.]
[562000.]


In [79]:
print("coef:", reg.coef_)
print("intercept:", reg.intercept_)

coef: [   86.25     0.   -4125.  ]
intercept: 408249.9999999999


### Metrics

In [80]:
from sklearn.metrics import mean_squared_error
import numpy as np
print("rsq:", reg.score(X_test, y_test))
np.sqrt(mean_squared_error(y_test, reg.predict(X_test)))

rsq: 0.8322115384615385


39937.940138419755

### Summary

In [81]:
import warnings
warnings.simplefilter(action='ignore')
import statsmodels.api as sm
model = sm.OLS(y_train, X_train).fit()
predictions = model.predict(X_test)

print_model = model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:                  price   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Sun, 06 Nov 2022   Prob (F-statistic):                nan
Time:                        23:03:03   Log-Likelihood:                 58.644
No. Observations:                   3   AIC:                            -111.3
Df Residuals:                       0   BIC:                            -114.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
area          86.2500        inf          0        n

## asgn3

In [82]:
from word2number import w2n
import math
hr = pd.read_csv("hiring.csv")
print(type(hr))
hr.experience = hr.experience.fillna("zero")
hr

<class 'pandas.core.frame.DataFrame'>


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [83]:
hr.experience = hr.experience.apply(w2n.word_to_num)
print(hr)
median_test_score = math.floor(hr["test_score(out of 10)"].mean())
print(median_test_score)
hr["test_score(out of 10)"] = hr["test_score(out of 10)"].fillna(median_test_score)
hr

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000
7


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

### single iv

In [84]:
X = hr["experience"].astype('category')
y = hr["salary($)"]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=1)
reg = LM()
reg.fit(X_train.values.reshape(-1, 1), y_train)

LinearRegression()

In [85]:
reg.coef_, reg.intercept_

(array([2352.45901639]), 52040.983606557376)

In [86]:
X = hr["experience"]
y = hr["salary($)"]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=1)
reg1 = LM()
reg1.fit(X_train.values.reshape(-1, 1), y_train)

LinearRegression()

In [87]:
reg1.coef_, reg1.intercept_

(array([2352.45901639]), 52040.983606557376)

### Metrics

In [96]:
from sklearn.metrics import mean_squared_error
print("rsq:", round(reg.score(X_test.values.reshape(-1, 1), y_test), 2))
print("rmse:", round(np.sqrt(mean_squared_error(y_test.values.reshape(-1, 1), reg.predict(X_test.values.reshape(-1, 1)))), 2))

rsq: 0.91
rmse: 3065.9


### Summary

In [97]:
import statsmodels.api as sm
model = sm.OLS(y_train, X_train).fit()
predictions = model.predict(X_test)

print_model = model.summary()
print(print_model)

                                 OLS Regression Results                                
Dep. Variable:              salary($)   R-squared (uncentered):                   0.634
Model:                            OLS   Adj. R-squared (uncentered):              0.561
Method:                 Least Squares   F-statistic:                              8.656
Date:                Sun, 06 Nov 2022   Prob (F-statistic):                      0.0322
Time:                        23:09:21   Log-Likelihood:                         -71.658
No. Observations:                   6   AIC:                                      145.3
Df Residuals:                       5   BIC:                                      145.1
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

### multi iv

In [106]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression as LM
X = hr.drop(["salary($)"], axis="columns")
y = hr["salary($)"]
print(type(x))
print(type(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=1)
reg = LM()
reg.fit(X_train, y_train)
print(reg.score(X_test, y_test))
print(reg.predict([[2,9,6]]))
print(reg.predict([[12,10,10]]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
0.9167614909316278
[53704.80156786]
[94927.56818553]


In [107]:
reg.coef_, reg.intercept_

(array([2938.755512  , 2890.24987751, 2236.24040503]), 8397.599216070586)

### Metrics

In [108]:
from sklearn.metrics import mean_squared_error
print("rsq:", round(reg.score(X_test, y_test), 2))
print("rmse:", round(np.sqrt(mean_squared_error(y_test, reg.predict(X_test))), 2))

rsq: 0.92
rmse: 2885.11


### Summary

In [109]:
import statsmodels.api as sm
model = sm.OLS(y_train, X_train).fit()
predictions = model.predict(X_test)

print_model = model.summary()
print(print_model)

                                 OLS Regression Results                                
Dep. Variable:              salary($)   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.998
Method:                 Least Squares   F-statistic:                              1291.
Date:                Sun, 06 Nov 2022   Prob (F-statistic):                    3.65e-05
Time:                        23:10:39   Log-Likelihood:                         -53.179
No. Observations:                   6   AIC:                                      112.4
Df Residuals:                       3   BIC:                                      111.7
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                                 coef    std err          t      P>|t|      [0.025      0.975]
-------------------------